"""Mechanical source adaptation for new201 permission; never runs the collector."""
from pathlib import Path
import ast
R=Path(__file__).parent
s=(R/'fixed_head_input_collector_v1.py').read_text(encoding='utf-8')
assert "range(0,232,32)" in s
s=s.replace('headFIT232','headEVAL201').replace('HEADFIT232','HEADEVAL201').replace('FIXED_HEAD232_LABEL_FREE_CANDIDATE_V1','FIXED_HEADEVAL201_FROZEN_NINE_READOUT_INPUTS_V1')
s=s.replace('candidate_collection_plan.json','matched_head_execution_plan.json').replace('fixed_reference_head_label_free_gate_v2','head_development_input_guard_v1')
s=s.replace("plan=read(bundle/'matched_head_execution_plan.json');e=read(a.evidence)","plan=read(bundle/'matched_head_execution_plan.json');e=read(a.evidence)\n    if plan['status']!='COMPLETE_MATCHED_HEAD_EXECUTION_PROTOCOL_FROZEN':raise PermissionError('FULL_EXECUTION_PROTOCOL_NOT_READY')\n    fitjoint=read(a.head_fit_joint)\n    if fitjoint['status']!='ACTUAL_HEADFIT232_GPU_PARENT_D_OTHER_CPU_FIT_SOURCE_STATE_CAPTURE_JOINT_PASSED' or fitjoint['plan_sha256']!=sha(bundle/'matched_head_execution_plan.json') or fitjoint['head_state_sha256']!=sha(a.head_state):raise PermissionError('ACTUAL_FIT_D_OTHER_CPU_COMPLETE_JOINT')\n    head=read(a.head_state)\n    if head['scope']!='FIXED_HEADFIT232_ONLY_U_W_AND_CONSTANT' or head['plan_sha256']!=sha(bundle/'matched_head_execution_plan.json') or head['headEVAL201_inputs_or_labels_used']:raise PermissionError('EXACT_FROZEN_FIT_HEAD_SCOPE')\n    if datetime.datetime.fromisoformat(head['actual_frozen_utc'])>=utc():raise PermissionError('FIT_HEAD_FROZEN_BEFORE201_INPUTS')\n    head_sha=sha(a.head_state)")
s=s.replace("rows=np.load(bundle/'head_development_fit_0.npy',allow_pickle=False)","rows=np.load(bundle/'head_development_eval_0.npy',allow_pickle=False)\n    fitrows=np.load(bundle/'head_development_fit_0.npy',allow_pickle=False)")
s=s.replace("records=allowed_head_inputs(session.guard._examples,rows,rows,allvideos)","if set(allvideos[int(i)] for i in rows)&set(allvideos[int(i)] for i in fitrows):raise PermissionError('HEAD_FIT_EVAL_VIDEO_OVERLAP')\n    records=allowed_head_inputs(session.guard._examples,rows,rows,allvideos)")
s=s.replace('len(dataset)==232','len(dataset)==201').replace('range(0,232,32)','range(0,201,32)').replace("'rows':232","'rows':201").replace("'forward_calls':34","'forward_calls':30").replace("'batch_sizes':[32]*7+[8]","'batch_sizes':[32]*6+[9]")
s=s.replace("'headEVAL201_inputs_or_labels_used':False","'headEVAL201_inputs_used':True,'headEVAL201_labels_used':False")
s=s.replace("final=budget('complete_original_arrays')","from matched_fixed_residual_heads_v2 import predict\n    readouts=predict(head['model'],arrays[0].astype(np.float64),delta,arrays[1].astype(np.float64))\n    np.savez_compressed(out/'frozen_headEVAL201_predictions.npz',row_ids=rows,head_state_sha256=np.asarray(head_sha),**readouts)\n    if sha(a.head_state)!=head_sha:raise ValueError('FROZEN_HEAD_CHANGED_DURING201_INFERENCE')\n    write(out/'nine_prediction_freeze.json',{'actual_utc':utc().isoformat(),'plan_sha256':sha(bundle/'matched_head_execution_plan.json'),'head_state_sha256':head_sha,'head_fit_joint_sha256':sha(a.head_fit_joint),'original_label_free_array_sha256':sha(out/'original_headEVAL201_label_free.npz'),'frozen_predictions_sha256':sha(out/'frozen_headEVAL201_predictions.npz'),'nine_readouts':list(readouts),'rows':rows.tolist(),'201_task_labels_indexed':False})\n    final=budget('complete_original_arrays_and_all_nine_readouts')")
s=s.replace("'original_array_sha256':sha(out/'original_headEVAL201_label_free.npz')","'original_array_sha256':sha(out/'original_headEVAL201_label_free.npz'),'frozen_predictions_sha256':sha(out/'frozen_headEVAL201_predictions.npz'),'nine_prediction_freeze_sha256':sha(out/'nine_prediction_freeze.json'),'head_state_sha256':head_sha,'head_fit_joint_sha256':sha(a.head_fit_joint)")
s=s.replace("'status':'ACTUAL_HEADEVAL201_ONE_CANDIDATE_LABEL_FREE_COLLECTION_COMPLETE_NOT_HEAD_FIT'","'status':'ACTUAL_HEADEVAL201_FROZEN_NINE_PREDICTIONS_LABEL_FREE_COMPLETE_NOT_SCORES'")
s=s.replace("p.add_argument('--out',required=True);run(p.parse_args())","p.add_argument('--head-state',required=True);p.add_argument('--head-fit-joint',required=True);p.add_argument('--out',required=True);run(p.parse_args())")
s=s.replace('One frozen best, headEVAL201 inputs only; no task label access or head fitting.','Future frozen heads + same best/candidate, exact201 dummy inputs; no true labels or scores.')
s=s.replace("plan=read(bundle/'matched_head_execution_plan.json');e=read(a.evidence)","plan=read(bundle/'matched_head_execution_plan.json')").replace("fitjoint=read(a.head_fit_joint)","e=read(a.evidence)\n    fitjoint=read(a.head_fit_joint)")
ast.parse(s);(R/'fixed_head_development_collector_v1.py').write_text(s,encoding='utf-8')
print('NEW201_COLLECTOR_SOURCE_WRITTEN_AST_ONLY_NOT_RUN')
