import sys,json,shutil,zipfile,hashlib,datetime
from pathlib import Path
root=Path(__file__).resolve().parent.parent;sys.path.insert(0,str(root/'work/anchored_increment_candidate'))
from common import sha,read,write
ref=read(root/'work/anchored_increment_pointer.json');d=Path(ref['D']);delivery=read(root/'outputs/原AnchoredFlow消息增量优化实际接续.json');report=Path(delivery['report']);out=report.parent;clock=sys.argv[1]
allrefs={k:read(d/k/'actual_D_verification.json') for k in ('A_native','B_native','A_cache','A_train','B_audit','A_integration')};assert all(v['natural_exit']==0 for v in allrefs.values());actual_integration=read(d/'A_integration/extracted/out/integration_result.json');assert actual_integration['check']['saved_trained_adapter_full_original_flow_formula_equivalence_maxerror']==0
arith=read(out/'independent_arithmetic_verification.json');assert arith['independent_five_metric_arithmetic_max_error']<1e-12
source=Path(read(d/'integration_source_reference.json')['source']);text=report.read_text(encoding='utf8')
append='\n## 完整原模型推理接入与封存\n\n`AnchoredMessageUpgrade` 已接回原两步流；加载原 selected_model 后替换 own_flow、加载保存的 adapter 即可。A 原Torch CUDA以真实best36流权重和实际新adapter进行随机状态集成检查，自然0，完整前向相对训练尾部公式误差严格0；dummy标签/填充值/批序及参数不变检查通过。这是合成状态接口核验，不冒新真实TEST分数。\n\n五项指标另用独立混淆计数/相关系数算术复核，最大差3.33e-16。所有新源、预测、状态、原capture及本报告已D保存，未额外删除原件。A/B两SSH及两SFTP明确exit/bye自然0关闭。\n'
report.write_text(text+append,encoding='utf8');shutil.copy2(source/'inference_upgrade.py',out/'inference_upgrade.py');shutil.copy2(d/'A_integration/extracted/out/integration_result.json',out/'actual_integration_result.json')
result=read(Path(delivery['result']));i=result['roles']['inner'];nw=i['metrics']['new_fixed20_message_on'];old=i['metrics']['old_best36_message_on'];p0=i['metrics']['p0_same_flow_off'];verdict=dict(actualclock_final_UTC=clock,all_original_archives=allrefs,original_training_natural_exit=0,updates=940,task_training_wall_seconds=result['train_result']['wall_seconds'],encoder_decoder_gain_fixed=True,whole_pipeline_OOF_residual_utility_gate_implemented=False,new_head_parameter_count=28848,INNER_new=nw,INNER_old=old,INNER_same_flow_off=p0,MAE_CI_vs_p0=i['paired_video_bootstrap_new_minus_baseline']['p0']['MAE'],all_five_strictly_improved=False,weak_improved_strong_slightly_worse=True,dropin_inference_actual=actual_integration,independent_metric_verification=arith,new_real_TEST_or_VAL_scores=False,whole_goal_complete=False,full_fivefold_complete=False,official_TEST_in_pooled_training=True,source_and_new_state_preservation='Full parent SHA plus complete changed adapter/Adam/RNG/orders; composite reconstruction, not standalone new full checkpoint',C_not_fresh=True,connections_closed_exit0=[16387,43123,42102,38604],fresh_auth_sessions_closed_exit1_without_authentication=[72971,23823],initial_parent_sha_read_error='System Python hashlib.file_digest AttributeError, corrected with private Python chunk hashing; actual SHA match recorded',no_additional_deletion=True,D_remaining_bytes=shutil.disk_usage(d).free,next='Keep original backbone. This single fixed experiment partially mitigated weak-sample dispersion but did not solve sign errors or all-five goal. Freeze new experiment before any further labels; genuine OOF utility estimator requires video-isolated backbone or explicitly limited conditional-frozen-backbone claim. No INNER-dependent width/loss/epoch sweep; no TEST-based architecture selection.')
write(out/'final_actual_joint_and_decision.json',verdict)
manifest={f.name:sha(f) for f in out.iterdir() if f.name!='member_SHA.json'};write(out/'member_SHA.json',manifest);zp=d/'final_original_increment_report.zip'
with zipfile.ZipFile(zp,'x',zipfile.ZIP_DEFLATED,6) as z:
    for f in out.iterdir():z.write(f,f.name)
with zipfile.ZipFile(zp) as z:
    assert z.testzip() is None and len(z.namelist())==len(set(z.namelist()))
    for n,h in manifest.items():assert hashlib.sha256(z.read(n)).hexdigest()==h
delivery.update(final_actualclock_UTC=clock,report_ZIP=str(zp),report_SHA=sha(zp),final_joint_SHA=sha(out/'final_actual_joint_and_decision.json'),inference_source=str(source/'inference_upgrade.py'),D_remaining_bytes=verdict['D_remaining_bytes'],all_four_connections_closed_natural0=True,new_real_TEST_or_VAL_scores=False)
write(d/'final_delivery.json',delivery);write(root/'outputs/原AnchoredFlow消息增量优化实际接续.json',delivery)
status=f'最新实际 {clock}：先读《原AnchoredFlow消息增量优化实际接续.json》及report。原best36全encoder/100维/两Euler/reader/decoder/gain冻结，只六供体400→8→100低秩donor-minus-zero分支28848参数、Huber1+.01context²，A2094固定20轮940步自然0/39.86秒；不是弱公共特征原型/完整OOF风险效用门。FIT1494原first状态缓存p0误差<=5.96e-6/state/RNG不变，A/B原native+全cache/state/D捕获B59863尾部CPU重放自然0；全Adam940两矩/20订单/RNG/new预测过。INNER264/11新五项50.3788%/86.4%/86.4070%/.622458224/.843017946，旧开MAE.640390996/同流关.632093474；弱.601410→.542284/强.668671→.680624，MAE相对p0配对CI[-.023853,+.003642]跨0/没有五项全胜。新Δ与p0线性R².688284/偏相关.122837，比旧近标量新样本内容更多但泛化未解决。全部六原capture SHA CRC唯一source/argv/PID自然0已D；新dropin原流接口A2230实际parent+adapter CUDA合成公式误差0，不冒CPUencoder前向/新实际VALTEST。独立指标算术误差3.33e-16。原3GB parent SHA继承+完整小变更state可组合重建，不冒standalone整新模型；D约{verdict["D_remaining_bytes"]}B，未额外删。4新会话16387/43123/42102/38604明确exit/bye0；此前72971/23823认证前关闭1保留，不复用。INNER已探索/原官方TEST已合并，非独立官方TEST/CaReFlow共同预算/完整五折，全部目标未完成。下一先真视频隔离残差效用泛化与符号问题，不扫INNER参数/TEST挑结构；C未fresh/原10min不改。以下历史。\n\n'
p=root/'outputs/研究接续状态.md';p.write_text(status+p.read_text(encoding='utf8'),encoding='utf8')
local=d/'local_final_operator_evidence';local.mkdir()
for f in [out/'final_actual_joint_and_decision.json',out/'independent_arithmetic_verification.json',root/'outputs/原AnchoredFlow消息增量优化实际接续.json',Path(__file__),root/'work/freeze_anchored_increment.py',root/'work/advance_anchored_plan.py',root/'work/freeze_anchored_integration.py',root/'work/score_anchored_increment.py']:shutil.copy2(f,local/f.name)
write(local/'SHA_manifest.json',{f.name:sha(f) for f in local.iterdir()})
print(json.dumps(dict(delivery=delivery,INNER_new=nw['overall'],D_remaining=verdict['D_remaining_bytes']),ensure_ascii=True))
