"""Freeze complete scientific/source protocol before any new supervised access."""
import ast,datetime,hashlib,json,shutil,sys,zipfile
from pathlib import Path
import numpy as np
R=Path(__file__).parent.parent;W=R/'work';O=R/'outputs';stamp=sys.argv[1];now=datetime.datetime.strptime(stamp,'%Y%m%dT%H%M%SZ').replace(tzinfo=datetime.timezone.utc).isoformat()
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
read=lambda p:json.loads(Path(p).read_text(encoding='utf-8'))
def write(p,x):Path(p).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
old=W/'fixed_head_candidate_collection_v1_20261006T191103Z';bundle=W/('matched_head_execution_v1_'+stamp);bundle.mkdir(exist_ok=False)
for p in old.iterdir():
 if p.is_file():shutil.copyfile(p,bundle/p.name)
new=['matched_fixed_residual_heads_v1.py','matched_fixed_residual_heads_v2.py','fit_matched_fixed_heads_original_v1.py','audit_matched_head_fit_original_CPU_v1.py','matched_head_fit_stage_wrapper_v1.py','head_development_input_guard_v1.py','fixed_head_development_collector_v1.py','score_frozen_matched_heads201_v1.py','matched_head_natural_stage_wrapper_v1.py','matched_development_independent_math_v1.py','audit_matched_development_arrays_CPU_v1.py','audit_matched_development_scores_CPU_v1.py','capture_fixed_matched_heads_v1.py','matched_head_capture_natural_wrapper_v1.py','join_matched_head_saved_stage_v1.py','sentiment_metrics_careflow_v1.py','check_matched_head_preparation_v2.py','check_matched_development_preparation_v1.py']
for n in new:ast.parse((W/n).read_text(encoding='utf-8'));shutil.copyfile(W/n,bundle/n)
for n in ['check_matched_head_preparation_v2.json','check_matched_development_preparation_v1.json']:shutil.copyfile(W/n,bundle/n)
fitrows=np.load(bundle/'head_development_fit_0.npy',allow_pickle=False);evalrows=np.load(bundle/'head_development_eval_0.npy',allow_pickle=False);mapping=read(bundle/'train_row_video_mapping.json')
assert len(fitrows)==232 and len(evalrows)==201 and len(np.unique(fitrows))==232 and len(np.unique(evalrows))==201 and not set(fitrows)&set(evalrows)
assert len({mapping[int(i)]['video_id'] for i in fitrows})==len({mapping[int(i)]['video_id'] for i in evalrows})==9 and not {mapping[int(i)]['video_id'] for i in fitrows}&{mapping[int(i)]['video_id'] for i in evalrows}
parent=read(old/'candidate_collection_plan.json');tests={n:read(W/n) for n in ['check_matched_head_preparation_v2.json','check_matched_development_preparation_v1.json']}
plan={'status':'COMPLETE_MATCHED_HEAD_EXECUTION_PROTOCOL_FROZEN','actual_frozen_utc':now,'source_and_role_sha256':{p.name:sha(p) for p in bundle.iterdir() if p.is_file()},'candidate_joint_sha256':'da44e83279048a7e615ca6ee5cc2cd20e3d251a054c5812f79a857972154aed0','reference_joint_sha256':parent['reference_joint_sha256'],'original_headFIT232_array_sha256':'c18a2510e3798c8ddee8d9cbdc019d5542e71d18a55a6e4f627cbfb80aa1db84','official_mosi_pickle_sha256':'5c3cc6ab6b43c97d3e34b9767b456d8e48f9bc5cc6f02089292a29d0e0aafd4b','checkpoint_file_sha256':parent['checkpoint_file_sha256'],'checkpoint_state_sha256':parent['checkpoint_state_sha256'],'FIT_statistics_sha256':parent['FIT_statistics_sha256'],'authorized_GPU_UUIDs':['GPU-53696803-875e-eec8-2231-29db63579891','GPU-8897bd58-4213-b200-8801-6ac6bfc55f3f','GPU-417d3577-0525-788b-7296-0808a0f52012'],
 'reference_and_candidate':'One saved best41 full FIT695 reference; identical first-context six incoming zero candidate and full second Euler; no teacher/seed/loss/candidate/amplitude/model update.',
 'roles':'Only reserved232/9 true TRAIN row labels for head fitting. Frozen heads before exact201/9 dummy inputs. All nine disk predictions/source/IDs/ownhead SHA before201 y once. INNER/referenceFIT/DEV/TEST/CAL labels not newly accessed. Trusted pickle contains unused labels; only allowed row label slots indexed.',
 'design':'Z=(pF,delta),r=y-pF. Common FIT232 a_i=1/(9*n_v). FIT-only population mean/std shared by U/W, exact constant feature column and slope0. No epsilon/extra inputs/201 statistics. Three slots explicit intercept+two standardized slopes.',
 'objectives':'U=sum a_i*(Xtheta-r)^2+.01*(beta^2+gamma^2). W q=a_i*4delta^2/c, c=sum a_i*4delta^2, sumq1 globally; same ridge .01 slopes, unpenalized intercept; no extra mean or1/2. Same float64 normal-equation solver, independent augmentedlstsq arithmetic audit. RawstructuredQ ridge equals c*.01.',
 'baselines_and_readouts':['F','C','constant_free','U_free','U_interval','U_discrete','W_free','W_interval','W_discrete'],
 'readouts':'F/C are saved real FP32 predictions represented float64. Constant k=a@(y-pF). Free=pF+h. Interval=pF+clip(h,min(0,delta),max(0,delta)). Discrete chooses savedpC iff delta²-2delta*h<0 elseF includingtie. Same rules for negative/zero delta. No output clip except Acc7 scoring.',
 'evaluation':'All nine same pooled author Acc7 clip-round; nonzero labels/pred>=0 Acc2 and support-weightedF1; original MAE/Pearson; pooled MSE plus same videoequalMSE and pervideo pairedQ. Main W-vs-U each samefree/interval/discrete; withinhead interval/discrete-vs-free. No201 choice of head/readout/lambda/feature/deployment winner. All five pointwise directions required for an exploratory allmetric benefit; no averaging failed metrics.',
 'stop':'Engineering/source/role/finite/replay mismatch invalidates affected stage; no row dropping. Exact FIT delta0 stops W/selection before newlabels; exactabsdelta constant U/W algebraicduplicate recorded; no empiricalESS/coverage/condition gate. No expansion when weighted or constrained outputs fail matched simplefree/constant. Do not change recipe from FIT objectives or201 scores. Newinputs/functionclass/confirmation need separately frozen protocol.',
 'chronology_and_preservation':'Complete protocol D/source SHA before first232 label. Common design physicalSHA before232 labels, one fitting state disk replay and full arrays/naturalexit saved D+othernode originalCPU/captures joint before201 inputs. Exact201 F-C-C-F per fixed32*6+9, firstbatchdummy0/7, wholeparameter/FITstats/RNG immutable and firstEuler identical. Allnine physicalfreeze saved D+othernode originalarrayaudit/captures joint before201 labels. Scoreonce and allnine/pervideo saved D+othernode independentmetrics/captures joint. This protocol does not unlock final TEST.',
 'budget':{'execution_seconds_per_stage':1200,'GPU_cumulative_peak_bytes':6*1024**3,'remote_free_bytes':4*1024**3,'D_free_bytes':6*1024**3,'save_reserve_seconds':7200,'fresh_query_max_seconds':300,'conservative_lease_end_UTC':'2026-10-07T13:30:00+00:00','platform_lease_confirmed':False},
 'human_asset_provenance':'Human newthree P4 second24h instruction20261006 and real freshSSH queries required. JSON cannot establish ownership/provenance. No old endpoints/credential files/guessing or bypass afterapproval rejection.',
 'scope':'One development exploration, TRAIN historically explored and INNER selected; not independent confirmation/wholecrossfit/CaReFlow benchmark/seedstability. Five-metric full target remains incomplete.',
 'synthetic_preparation_tests':tests,'actual_head_supervision_fit_or201_inference_or_scores_yet':False,'formal_protocol_frozen_not_runtime_passed':True}
write(bundle/'matched_head_execution_plan.json',plan);pkg=bundle.with_suffix('.zip')
with zipfile.ZipFile(pkg,'x',zipfile.ZIP_DEFLATED) as z:
 for p in bundle.iterdir():z.write(p,p.name)
with zipfile.ZipFile(pkg) as z:
 assert z.testzip() is None and len(z.namelist())==len(set(z.namelist()))
 for p in bundle.iterdir():assert hashlib.sha256(z.read(p.name)).hexdigest()==sha(p)
D=Path('D:/CodexBackups/selective_flow_20261003_1105')/('matched_head_execution_source_freeze_'+stamp);D.mkdir(exist_ok=False)
shutil.copytree(bundle,D/'source');shutil.copyfile(pkg,D/'source.zip');assert sha(D/'source.zip')==sha(pkg)
record={'status':'COMPLETE_MATCHED_HEAD_PROTOCOL_SOURCE_FROZEN_AND_D_PRESERVED_NOT_RUNTIME_EXECUTED','actual_utc':now,'bundle':str(bundle),'zip':str(pkg),'D':str(D),'plan_sha256':sha(bundle/'matched_head_execution_plan.json'),'bundle_zip_sha256':sha(pkg),'members':len(list(bundle.iterdir())),'fresh_C_D_free_bytes':{x:shutil.disk_usage(x+':/').free for x in ('C','D')},'actual_HEADFIT232_fit_or201_inputs_labels_scores':False,'next_required':['real fresh human lease identity/fullargv/emptycompute/assets/source/space gate','onceFIT CPU execution then completeD/otherCPU/captures joint before201 inference'],'local_test_repair':'Synthetic incompleteprotocol test detected evidence opened before protocol guard in new never-run201 collector; moved plan guard ahead of evidence. Original232 completedsource unchanged; failednever-run candidate retained.'}
write(D/'source_freeze_receipt.json',record);write(O/'完整流匹配U_W头执行源冻结最新.json',record)
(O/'完整流匹配U_W头执行源冻结接续.md').write_text('完整匹配U/W小实验执行源已冻，尚未执行\n\n'+now+'，plan SHA '+record['plan_sha256']+'。完整232 FIT标签/设计先冻、201 dummy与九预测先冻/一次评分、异节点原数组/独立指标、自然退出/capture/联合审核源和角色已保存D '+str(D)+'。所有算法/比较/指标/成本停止按第15数学细化共同固定，不从201选读出。\n\n合成201守卫6负门/3不完整协议入口拒绝、九预测独立重建0、五项独立算术差8.88e-16。仅本地源准备；无官方头标签、201输入或新成绩，实际Torch201/远端预算/CPU原件/capture未运行，不冒通过。旧准备版本/新collector未运行修复前源均保留。下一按已有授权fresh资产门后执行一次FIT，不用再等建议；完成D+异节点CPU/capture联结才201。\n',encoding='utf-8')
ledger=read(O/'研究建议交流接续.json');ledger['updated_at_utc']=now;ledger['matched_head_full_execution_source_freeze']=record;write(O/'研究建议交流接续.json',ledger)
state=O/'研究接续状态.md';state.write_text('源冻结UTC '+now+'：完整匹配232 FIT→201九预测锁定→一次development五项/MSE→原CPU/capture联合源已冻D，尚未真实FIT/201输入标签。plan '+record['plan_sha256']+'。先读完整流匹配U_W头执行源冻结接续.md/最新.json；源完整不等于运行通过，按现有授权下一fresh资产/空间/2h门后执行一次FIT并D+异节点CPU，禁重跑100/232候选和旧源。\n\n'+state.read_text(encoding='utf-8'),encoding='utf-8')
print(json.dumps(record))
