from pathlib import Path
import json,datetime,hashlib
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
rpath=Path('D:/CodexBackups/selective_flow_20261003_1105/finite_followup_20261005T1556Z/c/secondorder_receipt.json');r=json.loads(rpath.read_text());rp=json.loads(rpath.with_name('secondorder_plan.json').read_text())
assert r['source_sha256']==rp['source_sha256']==sha('work/check_single_token_secondorder_v1.py')
assert r['reader_source_sha256']==sha('work/finite_single_token_reader_v1.py') and r['train_rows']==[620,0] and not r['dev_requested'] and not r['test_requested']
for k in ['terminal_hvp_finite','main_head_gradients_none','aux_donor_gradients_none','frozen_gradients_none','coordinate_gradients_none','inference_zero_signal_exact','frozen_parameters_unchanged']:assert r[k]
fd=r['double_unrolled_finite_difference'];assert fd['error']<max(2e-6,2e-3*abs(fd['analytic'])) and r['label_replacement_error']==r['train_no_grad_error']==0
Path('outputs/单token解析分支专门二阶与梯度隔离独立核验.json').write_text(json.dumps(dict(status='SINGLE_TOKEN_SECONDORDER_ORIGINAL_RECEIPT_SOURCE_AND_FLAGS_INDEPENDENTLY_AUDITED',utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),receipt=r,plan=rp),ensure_ascii=False,indent=2),encoding='utf-8')
plan=json.loads(Path('work/finite_formal_plan_v1.json').read_text());plan.update(status='FROZEN_C2_AFTER_C1_NUMERICAL_FAILURE_BEFORE_REVISED_FORMAL100',utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),amendment_id='C2_ANALYTIC_SINGLE_VALID_TOKEN_READER',deployment='/data/coding/finite_task_risk_c2_deployment_20261005T1600Z',arms={'c2':'finite_vector'},original_failed_root='/data/coding/finite_task_risk_v1_deployment_20261005T1450Z',original_control_roots={'a':'/data/coding/finite_task_risk_v1_deployment_20261005T1450Z','b':'/data/coding/finite_task_risk_v1_deployment_20261005T1450Z'},expected_original_shared_phase_sha256='32fad83f206b32f4070fe2bbf0b3a588c1e8a5340c58b337a8e7052161c08088')
plan['scope']+=' C2 changes only numerical graph of analytic one-valid-token centeredcosine=0, otherrows original F.cosine; frozen parameter values/state identical. Original v1 C failure retained. A/B controls completed and not retrained. AllTRAIN shared10 forward exactly matches, sharedwarmup tensors exactly equal; C2 is disclosed amended arm, not original three-arm v1 success.'
plan['source_sha256']={n:sha('work/'+n) for n in ['finite_task_risk_feedback_v1.py','finite_task_risk_runtime_v1.py','finite_single_token_reader_v1.py','finite_task_risk_runtime_v2.py','train_finite_task_risk_v2.py','run_finite_training_wrapper_v2.py']}
proofs=['单token解析分支TRAIN机制独立核验.json','单token解析分支初始化订单共享期与原输入独立核验.json','单token解析分支专门二阶与梯度隔离独立核验.json']
plan['amendment_prechecks']={n:dict(sha256=sha(Path('outputs')/n),original_audit=json.loads((Path('outputs')/n).read_text(encoding='utf-8'))) for n in proofs}
plan['budget'].update(number_of_new_formal_arms=1,new_arm_epochs=100,expected_minutes=90,maximum_budget_estimate_minutes=120,no_restart_completed_controls=True,not_authorization_to_stop_healthy_training=True)
Path('work/finite_formal_plan_v2.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2),encoding='utf-8');Path('outputs/有限任务风险C2修订100轮冻结计划.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2),encoding='utf-8');print('C2_FORMAL_PLAN_FROZEN',sha('work/finite_formal_plan_v2.json'),fd)
