from pathlib import Path
import datetime,hashlib,json,zipfile
root=Path(__file__).resolve().parents[1];out=root/'outputs';anchor=root/'work/lease_202610050610Z/c/new';proof=json.loads((anchor/'proof.json').read_text());raw=(anchor/'snapshot.zip').read_bytes();assert hashlib.sha256(raw).hexdigest()==proof['archive_sha256'];dep='inflow_counterfactual_v5_deployment_20261005T0520Z';prefix=dep+'/run_predicted/'
with zipfile.ZipFile(anchor/'snapshot.zip') as z:
 hraw=z.read(prefix+'history.json');praw=z.read(prefix+'protocol.json');shared=z.read(prefix+'shared_phase.json');orders=z.read(prefix+'batch_orders.npy')
 for n,b in [('history.json',hraw),('protocol.json',praw),('shared_phase.json',shared),('batch_orders.npy',orders)]:assert hashlib.sha256(b).hexdigest()==proof['members'][prefix+n]['sha256'] and len(b)==proof['members'][prefix+n]['bytes']
 history=json.loads(hraw);assert len(history)==81 and [r['epoch'] for r in history]==list(range(1,82));best=min(history,key=lambda r:r['valid_mse']);assert best['epoch']==72 and history[-1]['best_epoch']==72 and history[-1]['best_valid_mse']==best['valid_mse']
 cp_entries=[e for e in proof['excluded_weights'] if e['path'].endswith('/'+dep+'/run_predicted/best.pt')];assert len(cp_entries)==1
 provisional=Path('D:/CodexBackups/selective_flow_20261003_1105/counterfactual_provisional_202610050542Z/c');receipt=json.loads((provisional/'provisional_receipt.json').read_text());old=json.loads((provisional/'source_history.json').read_text());assert len(old)==31 and min(old,key=lambda r:r['valid_mse'])['epoch']==30 and history[:31]==old
 report={'status':'C_81_EPOCH_RECOVERY_ANCHOR_VERIFIED_FINAL_CHECKPOINT_ABSENT','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'captured_at':proof['captured_at'],'archive_sha256':proof['archive_sha256'],'verified_history_epochs':81,'best_so_far_epoch':72,'best_so_far_author_batch_mse':best['valid_mse'],'previous_provisional_epochs':31,'previous_provisional_best_epoch':30,'previous_provisional_best_mse':min(old,key=lambda r:r['valid_mse'])['valid_mse'],'protocol_sha256':hashlib.sha256(praw).hexdigest(),'orders_file_sha256':hashlib.sha256(orders).hexdigest(),'shared_phase_file_sha256':hashlib.sha256(shared).hexdigest(),'latest_excluded_checkpoint_stat_only':cp_entries[0],'latest_checkpoint_content_sha256_available':False,'current_final_weight_available':False,'recoverable_completion_best_epoch_candidates':[72]+list(range(82,101)),'limits':['Latest excluded weight stat is not a weight SHA or a saved weight.','81-epoch history is not 100 completion or final selection.','31-epoch provisional weight cannot substitute for epoch72 best-so-far or final completion.','If original protocol and exact history prefix hold, final minimum cannot return to epoch30.','No C final predictions or MAE available; no three-arm performance claim.']}
with (out/'C恢复81轮锚点与材料边界.json').open('x',encoding='utf-8') as f:json.dump(report,f,ensure_ascii=False,indent=2)
lines=['# C恢复锚点与最低材料','','已核对14:10新snapshot及相关成员SHA。C正式predicted运行截至81轮，best-so-far已为72轮；31轮临时副本的best30已不是最后观察的最优。这里没有取得72轮权重内容或100轮最终选模。','',f"最后观察81轮内最小作者批次等权DEV MSE为{best['valid_mse']:.10f}，仅用作恢复历史核验锚点，不能作为完成实验的指标。",'', '新取回history必须连续1..100且前81条逐字段完全等于已保存历史；protocol、100订单文件及shared_phase必须与锚点逐字节一致。每轮best记录及100轮全局最小选模重新计算；选中阶段<=10时恢复fixed的规则仍保留。当前锚点下最终best只能是72或82..100，不能回填为30。','', '最低工件为七核心文件best.pt、protocol.json、batch_orders.npy、history.json、selection.json、results.json、predictions.npz；shared_phase.json额外必须保留。完整best.pt>700MB，全文件SHA绑定selection，并独立核验Torch ZIP完整CRC；229预测/标签、六方向u/权重、own、fixed参考及all-off全部核验。文件体积相等不证明权重相同，旧31轮与最后观察best.pt恰好同体积，不能据此复用。','', '工具work/verify_recovered_counterfactual_artifacts_v1.py已在A的真实完整工件上通过；它仅证明CPU工件一致性，不证明原训练进程完成时刻、当前GPU身份或PyTorch权重重放。当前C临时目录必须拒绝为最终材料。','', '取回材料后还需要真实目标GPU UUID及来源记录、冻结权重原方法229重放、预定29条件诊断和独立节点七文件CPU SHA。可用新节点恢复时应单独记录实际目标UUID；不能冒充原C UUID，不能修改已冻结训练源。当前无有效新节点信息，不执行任何连接、重训或新训练。','', '13:40/14:10保存证明保持；14:30真实capture仍缺失。当前恢复也不能补记该期限。A独立CPU原回执文件如可取得应原样下载并与保存的终端证据比对，不能由摘要重建原回执。', '', '现有材料会永久保留，所有新材料使用新目录/文件名。官方TRAIN1281/dev229，不访问TEST选结构，不称五seed稳定/SOTA/共享补充干扰真值。']
(out/'C恢复锚点与最低材料.md').write_text('\n'.join(lines)+'\n',encoding='utf-8');print(json.dumps({'status':report['status'],'best_so_far_epoch':best['epoch']}))
