from pathlib import Path
import ast,datetime,hashlib,json,shutil
w=Path(__file__).resolve().parent;r=w/'inflow_counterfactual_v5_deployment_20261005T0520Z';r.mkdir(exist_ok=False)
sdir=w/'inflow_counterfactual_v5_checks_20261005T0516Z'
audit=json.loads((w.parent/'outputs/主任务反事实效用机制检查核验.json').read_text(encoding='utf-8'));assert audit['status']=='THREE_MATCHED_GPU_MECHANISM_CHECKS_VERIFIED'
for name in ['counterfactual_flow_model.py','encoder_adapter.py','legacy_flow_model.py']:(r/name).write_bytes((sdir/name).read_bytes())
s=(sdir/'check_counterfactual_v5.py').read_text();s=s[:s.index("    assert cli.stage=='check'")]
s=s.replace('choices=("check",)','choices=("run",)').replace('check_counterfactual_v5.py','run_counterfactual_v5.py').replace('inflow_counterfactual_v5_check','inflow_counterfactual_v5')
s=s.replace('20 mechanism updates only;','100 matched epochs;').replace('"test_policy": "TEST forbidden; selected checkpoint end dev/default and predetermined frozen condition-off only"','"test_policy": "TEST forbidden; selected epoch determines effective phase; end dev/default and fixed condition-off only"')
old=(w/'inflow_utility_v4_20261005T0346Z/run_inflow_utility_v4.py').read_text();tail=old[old.index('    history, best, best_epoch = []'):]
tail=tail.replace('        losses = train_epoch','        core.own_flow.set_epoch(epoch)\n        losses = train_epoch')
tail=tail.replace('        valid = author.eval_epoch(model, valid_loader)','        if epoch==10:\n            helpers.write(cli.out / "shared_phase.json", {"epoch":10,"model_sha256":tensor_state_sha(model),"batch_order_sha256":protocol["batch_order_sha256"]})\n        valid = author.eval_epoch(model, valid_loader)')
tail=tail.replace('"last_train_batch_utility_weights"','"last_dev_batch_utility_weights"').replace('"checkpoint_sha256": helpers.digest','"selected_effective_mode": "fixed" if best_epoch<=10 else cli.mode,\n                 "checkpoint_sha256": helpers.digest')
tail=tail.replace('    valid_metrics, vp, vy =','    core.own_flow.set_epoch(best_epoch)\n    valid_metrics, vp, vy =')
tail=tail.replace("('own','pair','utility','predicted_weights')","('own','pair','utility','predicted_weights','weights','reference_prediction')")
tail=tail.replace('INFLOW_UTILITY_RUN_COMPLETE','COUNTERFACTUAL_V5_RUN_COMPLETE')
s+=tail;ast.parse(s);(r/'run_counterfactual_v5.py').write_text(s)
manifest={'source_sha256':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in sorted(r.glob('*.py'))}};(r/'source_manifest.json').write_text(json.dumps(manifest,indent=2))
free=shutil.disk_usage('D:/').free;assert free>3_000_000_000
plan={'frozen_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'seed':91814,'epochs':100,'updates':4000,'shared_fixed_epochs':10,'modes':['none','fixed','predicted'],'estimand':'Feedback strategy after identical ten fixed-feedback epochs; none is not zero-feedback from initialization','expected_initial_sha':audit['rows'][0]['checks']['initial_model_sha256'],'expected_orders_sha':audit['rows'][0]['checks']['batch_order_sha256'],'mechanism_audit_sha256':hashlib.sha256((w.parent/'outputs/主任务反事实效用机制检查核验.json').read_bytes()).hexdigest(),'reference_paths_train':10,'reference_paths_eval':1,'tau':.05,'test_accessed':False,'measured_update_seconds_max':max(x['checks']['steady_update_seconds_mean'] for x in audit['rows']),'estimate_update_seconds':max(x['checks']['estimated_4000_update_seconds'] for x in audit['rows']),'reserve_dev_checkpoint_setup_seconds':600,'reserve_download_independent_cpu_seconds':300,'latest_launch_utc':'2026-10-05T05:22:00+00:00','deadline_preservation_utc':'2026-10-05T06:30:00+00:00','permanent_weights_directory':'D:/CodexBackups/selective_flow_20261003_1105/counterfactual_v5_completed_20261005','drive_D_free_bytes':free,'no_stopping_healthy_training':True,'selection':'minimum of100 official229 dev author batch128 MSE; effective mode at selected epoch retained','limits':'Exploratory one seed; no TEST structure selection/stability/SOTA/semantic truth. No renewal or old deletion.'}
(r/'frozen_plan.json').write_text(json.dumps(plan,indent=2))
launcher=(w/'launch_counterfactual_checks_v1.py').read_text().replace('inflow_counterfactual_v5_checks_20261005T0502Z','inflow_counterfactual_v5_deployment_20261005T0520Z').replace("assert json.loads((root/'check_plan.json').read_text())['budget_check_updates']==20","plan=json.loads((root/'frozen_plan.json').read_text());assert plan['epochs']==100 and plan['seed']==91814\nassert datetime.datetime.now(datetime.timezone.utc)<datetime.datetime.fromisoformat(plan['latest_launch_utc'])")
launcher=launcher.replace('check_launch.json','training_launch.json').replace('check.log','training.log').replace('check_counterfactual_v5.py','run_counterfactual_v5.py').replace("'--stage','check'","'--stage','run'").replace("'check_'+c.mode","'run_'+c.mode").replace("'--seed','91814']","'--seed','91814','--expected-initial-sha',plan['expected_initial_sha']]").replace("'stage':'mechanism_check_only'","'stage':'run'").replace("'check_plan.json'","'frozen_plan.json'").replace("'performance_training_started':False","'performance_training_started':True")
ast.parse(launcher);(r/'launch_counterfactual_v5.py').write_text(launcher)
cap=(w/'capture_counterfactual_followup_v2.py').read_text().replace("'inflow_counterfactual_v5_checks_20261005T0516Z')]","'inflow_counterfactual_v5_checks_20261005T0516Z',\n 'inflow_counterfactual_v5_deployment_20261005T0520Z')]")
ast.parse(cap);(w/'capture_counterfactual_followup_v3.py').write_text(cap)
print(json.dumps(plan));print(json.dumps(manifest))
