import datetime,hashlib,json,sys
from pathlib import Path
R=Path(__file__).parent.parent;O=R/'outputs';D=Path('D:/CodexBackups/selective_flow_20261003_1105/matched_head_fit_actual_20261006T194858Z');sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();read=lambda p:json.loads(Path(p).read_text(encoding='utf-8'))
def write(p,x):Path(p).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
joint=read(D/'complete_matched_headFIT232_D_B_CPU_joint.json');fit=read(D/'a/run/out/actual_matched_head_fit_receipt.json');ex=read(D/'a/run/natural_exit.json');cpu=read(D/'b/run/cpu_original_receipt.json');head=read(D/'a/run/out/head_state.json')
now=datetime.datetime.now(datetime.timezone.utc).isoformat();record={'status':joint['status'],'actual_record_utc':now,'D':str(D),'joint_sha256':sha(D/'complete_matched_headFIT232_D_B_CPU_joint.json'),'plan_sha256':joint['plan_sha256'],'original_FIT_child_pid':fit['pid'],'actual_FIT_natural_exit_utc':ex['actual_exit_utc'],'head_state_sha256':fit['head_state_sha256'],'original_supervised_array_sha256':fit['original_supervised_array_sha256'],'FIT_only_objectives_not_comparable_risks':fit['objective_FIT_only_not_generalization'],'U_coefficients_shared_standardized_features':head['model']['U'],'W_coefficients_shared_standardized_features':head['model']['W'],'constant_FIT_videoequal':head['model']['constant'],'FIT_elapsed_seconds':fit['elapsed_seconds'],'own_head_disk_replay_error':fit['whole_head_disk_replay_max_error'],'other_node_CPU_original_pid':cpu['pid'],'other_node_independent_augmented_lstsq_error':cpu['independent_augmented_lstsq_vs_normal_equation_max_error'],'new201_inputs_or_labels_in_this_FIT':False,'newGPU_or_teacher_update':False,'new_performance_or_CaReFlow_comparison':False,'complete_protocol_frozen_before_trueFIT_labels':True,'common_design_disk_SHA_before_labels':fit['before_label_common_design_sha256']}
write(O/'完整流匹配U_W头FIT232实际结果.json',record)
(O/'完整流匹配U_W头FIT232实际结果.md').write_text('完整流匹配U/W头FIT232实际拟合与原件保存\n\n'+now+'记录。child'+str(fit['pid'])+'在'+ex['actual_exit_utc']+'自然exit0，232/9允许行标签一次、共同FIT人口统计已先写盘SHA；U/W同3参数/斜率ridge .01/自由截距和共同常数已拟合，原head整JSON重放0。FIT耗时'+str(fit['elapsed_seconds'])+'秒，无GPU/参考更新/201输入或真标签。\n\n原异节点B NumPy child'+str(cpu['pid'])+'自然0，独立增广最小二乘差'+str(cpu['independent_augmented_lstsq_vs_normal_equation_max_error'])+'，原标签数组/设计/系数/目标/读出/源/自然退出核过，非CPU模型前向。完整D '+str(D)+'，A69/B134原capture完整SHA/CRC/unique联合通过。head SHA '+fit['head_state_sha256']+'；联合SHA '+record['joint_sha256']+'。\n\nU/W训练目标各使用不同权重，.556341/.372938不能横比作真实风险收益；没有201新五项成绩或CaReFlow超过证据。下一同一冻结head生成201 dummy九预测，完整保存/异节点原数组门后才一次评分，不能重拟合或挑读出。\n',encoding='utf-8')
state={'status':'FIT232_ORIGINAL_D_OTHER_CPU_JOINT_PASSED_NEXT201_PREDICTION_STAGE','actual_record_utc':now,'fit':record,'head_fit_remote_root':'/data/coding/fixed_head_matched_fit_20261006T194858Z','head_predict_remote_root':'/data/coding/fixed_head_matched_predict201_20261006T195233Z','predict_completed_or_scores':False,'sessions_current_turn':{'A_SSH':27749,'A_SFTP':52161,'B_SSH':28761,'B_SFTP':92646},'sessions_closed':False,'no_duplicate_fit_or100_or232_collection':True}
write(O/'完整流匹配U_W头实际接续.json',state)
ledger=read(O/'研究建议交流接续.json');ledger['updated_at_utc']=now;ledger['latest_matched_headFIT232_actual']=record;write(O/'研究建议交流接续.json',ledger)
p=O/'研究接续状态.md';p.write_text('实际FIT记录UTC '+now+'：匹配232/9 U/W+共同常数真实拟合child1926自然0、整head重放0、完整D+B原NumPy/capture总门已过。仅FIT目标非收益，201标签未读。先读完整流匹配U_W头FIT232实际结果.md/json与实际接续.json；201新根/data/coding/fixed_head_matched_predict201_20261006T195233Z状态须实际核，不能重启头或100。\n\n'+p.read_text(encoding='utf-8'),encoding='utf-8')
print(json.dumps({'status':record['status'],'joint_sha256':record['joint_sha256'],'new201_scores':False}))
