import json,hashlib,shutil,zipfile,sys
from pathlib import Path
clock=sys.argv[1];o=Path('outputs');read=lambda p:json.loads(p.read_text(encoding='utf8'));sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();rec=read(Path('work/weak_retention_current.json'));d=Path(rec['D']);control=d/'actual_control';control.mkdir()
exchange=o/'研究建议交流接续.json';shutil.copy2(exchange,control/'prior_exchange.json');x=read(exchange)
x['weak_gate_direct_optimization_batch']=dict(report_SHA=sha(o/'弱情绪直接修正对照与新训练方案实际结果.json'),D_result_complete_zip_SHA='c9c18b8fdd03b6b4791b33facd3ba07766ff12dc0531cea5eebc73b225afe0a9',thread_id='01a10fcb-6663-70a2-9a76-60e5634d0c03',turn_id='01a11666-ba56-75f1-9877-587bcb0707da',actualclock_record_UTC=clock,status='SENT_ONCE_AFTER_D_LOCAL_CPU_INDEPENDENT_CHECK_WAIT_ONCE_INPROGRESS',sent_once=True,wait_once=True,cursor='a752fe6f-3a58-446f-9d08-6606385560e1:3',complete_report_read_or_adopted=False,no_same_batch_retry=True,scope='Analysis only; fixed weak gate negative development result and training loss candidate; no remote/GPU/source edits or credentials',preservation_not_delayed=True)
exchange.write_text(json.dumps(x,ensure_ascii=False,indent=2),encoding='utf8')
failure=dict(actualclock_record_UTC=clock,operation='Fresh B SSH for CPU synthetic gradient check only',host='REDACTED_SERVER_HOST.invalid',port=53332,attempts=[dict(session_id=74934,exit_code=1),dict(session_id=97799,exit_code=1)],exact_error='Connection timed out during banner exchange; Connection to 198.18.0.33 port 53332 timed out',real_password_prompt_seen=False,credentials_sent=False,not_approval_rejection=True,not_claiming_server_down=True,synthetic_native_check_completed=False,do_not_reuse_sessions=True)
(control/'actual_connection_failures.json').write_text(json.dumps(failure,indent=2),encoding='utf8')
state=dict(status='DIRECT_WEAK_GATE_TEST_COMPLETE_REJECTED_NEW_WEAK_RETENTION_LOSS_CANDIDATE_PREPARED_NATIVE_CHECK_BLOCKED',actualclock_record_UTC=clock,gate_result=str(o/'弱情绪直接修正对照与新训练方案实际结果.json'),gate_result_SHA=sha(o/'弱情绪直接修正对照与新训练方案实际结果.json'),gate_D='D:/CodexBackups/selective_flow_20261003_1105/weak_prediction_gate_control_20261007T124056Z',candidate_D=rec['D'],candidate_plan_SHA=rec['plan_SHA'],candidate_source_zip_SHA=rec['source_zip_SHA'],GPU_training_started=False,no_new_TEST_scores=True,no_full5fold_complete=True,local_primary_and_independent_formula_metrics_actual=True,remote_native_synthetic_contract_verified=False,remote_connection_failure=failure,source_AST_verified=True,affine_OLS_not_executed=True,next_dynamic_UTC='2026-10-07T13:00:00+00:00',lease_end_conservative_UTC='2026-10-07T13:30:00+00:00',platform_expiry_confirmed=False,D_fresh_bytes=2463739904,C_fresh_bytes=620425216,pending_training_resource_requirements='New full training state needs about2.97GB plus reserve; current D2.46GB insufficient; time cannot satisfy training +2h saving.',review19_sent_waited_once=True,current_live_sessions=[])
(o/'弱情绪直接优化实际接续.json').write_text(json.dumps(state,ensure_ascii=False,indent=2),encoding='utf8')
st=o/'研究接续状态.md';shutil.copy2(st,control/'prior_short_state.md');st.write_text(f'最新直接优化{clock}：先读《弱情绪直接修正对照与新训练方案实际结果.md/json》《弱情绪直接优化实际接续.json》。固定模型预测弱门控q=b+b²/(1+b²)*(p−b)一次FIT/INNER本地CPU11996/不同公式独立CPU1284自然0/D全SHA/CRC唯一封存，非新GPU/remote capture/TEST重评分。INNER弱MAE .638971→.557799，但强.708821→.815040、整体.679452→.706882，四五项差，拒绝此固定门控不扫尺度。下一单损失候选仅FIT弱样本加入ReLU(final²error−stop_gradient(base)²error)均值固定系数1，原推理不变无真实标签门控；完整源码D/AST过，GPU disabled/未训练/无新收益。B新SSH74934/97799两次banner timeout明确exit1，无密码提示/未认证，非权限审批拒绝，不称serverdown或native验证通过。D2.46GB/剩余租期不足新完整训练状态+保存余量/至少2h；13:00实际三机动态保存仍待，不能回填或因等建议延误。第19批实质负结果已发一次/wait一次inProgress，完整建议未回按交流JSON，不重复轮询或发送。旧C2/F/C/A/B全部VALTEST完成保留，新20混合角色非独立TEST/完整五折未完成。原10分钟保持，整体目标未完成。以下均历史。\n\n'+st.read_text(encoding='utf8'),encoding='utf8')
for p in [exchange,st,o/'弱情绪直接优化实际接续.json',Path(__file__)]:shutil.copy2(p,control/p.name)
files=[p for p in control.iterdir() if p.is_file()];(control/'manifest.json').write_text(json.dumps(dict(actualclock_UTC=clock,member_SHA={p.name:sha(p) for p in files}),indent=2),encoding='utf8')
with zipfile.ZipFile(d/'complete_actual_control.zip','x',zipfile.ZIP_DEFLATED) as z:
 for p in files+[control/'manifest.json']:z.write(p,p.name)
with zipfile.ZipFile(d/'complete_actual_control.zip') as z:assert z.testzip() is None and len(z.namelist())==len(set(z.namelist()))
print(json.dumps(dict(status=state['status'],D_control_SHA=sha(d/'complete_actual_control.zip'))))
